Publish IdentityUpdates to blockchain and read back (#175)
## tl;dr

- Publishes IdentityUpdates to blockchain as part of the publsh API
- Fixes some bugs in the `IdentityUpdate` storing flow
- Prevents duplicate `IdentityUpdate`s from being saved

---------

Co-authored-by: Martin Kysel <code@martinkysel.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: mkysel <7513948+mkysel@users.noreply.github.com>

diff --git a/dev/generate b/dev/generate
--- a/dev/generate
+++ b/dev/generate
@@ -2,10 +2,15 @@
 
 set -euo pipefail
 
+rm -rf pkg/proto/**/*.pb.go pkg/proto/**/*.pb.gw.go pkg/proto/**/*.swagger.json
+if ! buf generate https://github.com/xmtp/proto.git#subdir=proto,branch=main; then
+    echo "Failed to generate protobuf definitions"
+    exit 1
+fi
+
 go generate ./...
 rm -rf pkg/mocks/*
 ./dev/abigen
 mockery
 sqlc generate
-
 ./dev/gen_protos
