output to temporary logs

diff --git a/contracts/dev/deploy-local b/contracts/dev/deploy-local
--- a/contracts/dev/deploy-local
+++ b/contracts/dev/deploy-local
@@ -13,31 +13,44 @@ cd "${repo_root}"
 source dev/lib/env
 source dev/lib/common
 
-# Ensure there are no old artifacts
-forge clean
-
-echo -e "⧖ Updating dependencies"
-forge soldeer update -q
+echo -e "⧖ Cleaning old artifacts"
+forge clean &> forge_clean.log
 if [ $? -ne 0 ]; then
-  echo "ERROR: Failed to update dependencies"
+  echo "ERROR: Failed to clean old artifacts"
+  cat forge_clean.log
   exit 1
 fi
+rm forge_clean.log
+echo -e "✔ Old artifacts cleaned successfully\n"
+
+echo -e "⧖ Updating dependencies"
+forge soldeer update &> forge_soldeer_update.log
+if [ $? -ne 0 ]; then
+  echo "ERROR: Failed to update dependencies"
+  cat forge_soldeer_update.log
+  exit 1
+fi
+rm forge_soldeer_update.log
 echo -e "✔ Dependencies updated successfully\n"
 
 echo -e "⧖ Building contracts"
-forge build -q
+forge build &> forge_build.log
 if [ $? -ne 0 ]; then
   echo "ERROR: Failed to build contracts"
+  cat forge_build.log
   exit 1
 fi
+rm forge_build.log
 echo -e "✔ Contracts built successfully\n"
 
 echo -e "⧖ Running contract tests"
-forge test -q
+forge test &> forge_test.log
 if [ $? -ne 0 ]; then
   echo "ERROR: Tests failed"
+  cat forge_test.log
   exit 1
 fi
+rm forge_test.log
 echo -e "✔ Tests passed successfully\n"
 
 forge_deploy_script group_messages
