Make RatesManager upgradeable and deployable

diff --git a/contracts/dev/lib/common b/contracts/dev/lib/common
--- a/contracts/dev/lib/common
+++ b/contracts/dev/lib/common
@@ -37,6 +37,17 @@ function forge_deploy_script() {
             echo -e "\033[32m✔\033[0m Nodes deployed. Deployment details in contracts/config/anvil_localnet/$3.json\n"
             ;;
 
+        rates_manager)
+            echo "⧖ Deploying RatesManager to chainId ${chain_id} using RPC ${RPC_URL}"
+            forge script --quiet --rpc-url "${RPC_URL}" --broadcast script/DeployRatesManager.s.sol || BUILD_FAILED=true
+            if [[ -n "${BUILD_FAILED:-}" ]]; then
+                echo "Failed to deploy rates manager contract"
+                exit 1
+            fi
+
+            echo -e "\033[32m✔\033[0m RatesManager deployed. Deployment details in contracts/config/anvil_localnet/RatesManager.json\n"
+            ;;
+
         *)
             echo "Invalid option. Use 'group_messages', 'identity_updates' or 'nodes'."
             exit 1
