new linter

diff --git a/.github/workflows/lint-go.yml b/.github/workflows/lint-go.yml
--- a/.github/workflows/lint-go.yml
+++ b/.github/workflows/lint-go.yml
@@ -33,3 +33,15 @@ jobs:
         uses: nickcharlton/diff-check@main
         with:
           command: dev/lint-golines
+      - name: Generate Mocks and sqlc
+        run: dev/generate
+
+      - name: Check for ABI changes
+        working-directory: ${{ github.workspace }}
+        run: |
+          if git diff --exit-code --ignore-space-change --ignore-all-space --ignore-cr-at-eol -- pgk; then
+            echo "No ABI changes detected."
+          else
+            echo "ERROR: Generated files are not up to date. Please run 'dev/generate' and commit the changes."
+            exit 1
+          fi
